spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.platform=postgres

spring.jpa.open-in-view=false

spring.security.user.name=disabled
spring.security.user.password=disabled

server.port=8080

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.application.name=ecommerce
